-- 在 Supabase Dashboard -> SQL Editor 中完整运行此文件。

create table if not exists public.love_responses (
  id bigint generated by default as identity primary key,
  answer text not null,
  activity text,
  date date,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.love_responses enable row level security;

-- 前台允许匿名提交。
drop policy if exists "allow anonymous inserts" on public.love_responses;
create policy "allow anonymous inserts"
on public.love_responses
for insert
to anon
with check (true);

-- 注意：
-- 为了让前台不需要登录，anon key 可以提交。
-- 后台页面如果直接用 anon key 查询，则需要 SELECT policy。
-- 这种方案适合私人、小范围使用；如果公开传播链接，建议进一步做真正的管理员认证。
drop policy if exists "allow anonymous reads" on public.love_responses;
create policy "allow anonymous reads"
on public.love_responses
for select
to anon
using (true);